org.gradle.jvmargs=-Xmx5120M -XX:MaxMetaspaceSize=1024M -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.workers.max=1
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
android.enableR8.fullMode=true
kotlin.code.style=official
kotlin.mpp.androidGradlePluginCompatibility.nowarn=true

org.gradle.caching=true
org.gradle.configuration-cache=true
android.enableJetifier=false
android.nonTransitiveRClass=true